#!/bin/bash

if [[ -z "${SSHUSER}" ]]; then
  JAILED_USER=sshjail
  export BACKUP_USER=$JAILED_USER
else
  JAILED_USER="${SSHUSER}"
fi

groupadd jailed
adduser --disabled-password --shell /usr/bin/bash --ingroup jailed --gecos "" $JAILED_USER

mkdir -p /var/jail/home/$JAILED_USER
chown -R $JAILED_USER:jailed /var/jail/home/$JAILED_USER
chmod -R 700 /var/jail/home/$JAILED_USER

if [[ -z "${AUTH_KEY}" ]]; then

    if [[ -z "${SSHPASS}" ]]; then
        SSHPASS=sshjail
    else
        USER_PASS=$SSHPASS
    fi
    
else    
    mkdir /home/$JAILED_USER/.ssh && chown $JAILED_USER:jailed /home/$JAILED_USER/.ssh && chmod 700 /home/$JAILED_USER/.ssh
    echo "${AUTH_KEY}" >> /home/$JAILED_USER/.ssh/authorized_keys
fi

echo "# Automatically generated by mkuser.sh" > /etc/ssh/sshd_config
echo "Include /etc/ssh/sshd_config.d/*.conf" >> /etc/ssh/sshd_config
echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
echo "Subsystem sftp internal-sftp" >> /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
echo "PrintMotd no" >> /etc/ssh/sshd_config
echo "Banner none" >> /etc/ssh/sshd_config
echo "UsePam yes" >> /etc/ssh/sshd_config
echo 'PermitRootLogin no' >> /etc/ssh/sshd_config
echo 'PermitEmptyPasswords no' >> /etc/ssh/sshd_config
echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config
echo "LoginGraceTime 2m" >> /etc/ssh/sshd_config
echo "MaxAuthTries 3" >> /etc/ssh/sshd_config
echo "MaxSessions 2" >> /etc/ssh/sshd_config
echo "# Match section --\n" >> /etc/ssh/sshd_config
echo "Match User ${JAILED_USER}" >> /etc/ssh/sshd_config

if [[ -z "${SSHPASS}" ]]; then
  echo '  PasswordAuthentication no' >> /etc/ssh/sshd_config
else
  echo -e "$SSHPASS\n$SSHPASS" | passwd $JAILED_USER
  echo '  PasswordAuthentication yes' >> /etc/ssh/sshd_config
fi

